# Variáveis Categóricas e Separação em Teste e Treino - Machine Learning 02

### Importação

In [1]:
# Libs
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

### Base de Dados

In [2]:
# Dados
ds = pd.read_csv('admission.csv', sep=';')
ds.head()

Name  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA   
0    Lucas        337          118                  4  4.5  4.5  9.65  \
1      Ana        324          107                  4  4.0  4.5  8.87   
2     Jose        316          104                  3  3.0  3.5  8.00   
3   Carlos        322          110                  3  3.5  2.5  8.67   
4  Zileide        314          103                  2  2.0  3.0  8.21   

   Research  Approval  
0         1         1  
1         1         1  
2         1         1  
3         1         1  
4         0         0

### Separando os Valores

In [3]:
# Amostra
X =ds.iloc[:, 0:8].values
X

array([['Lucas', 337, 118, 4, 4.5, 4.5, 9.65, 1],
       ['Ana', 324, 107, 4, 4.0, 4.5, 8.87, 1],
       ['Jose', 316, 104, 3, 3.0, 3.5, 8.0, 1],
       ['Carlos', 322, 110, 3, 3.5, 2.5, 8.67, 1],
       ['Zileide', 314, 103, 2, 2.0, 3.0, 8.21, 0],
       ['Joana', 330, 115, 5, 4.5, 3.0, 9.34, 1],
       ['Davi', 321, 109, 3, 3.0, 4.0, 8.2, 1],
       ['Daniel', 308, 101, 2, 3.0, 4.0, 7.9, 0],
       ['Marcelo', 302, 102, 1, 2.0, 1.5, 8.0, 0]], dtype=object)

In [4]:
# Variável independente 
y = ds.iloc[:, 8].values
y

array([1, 1, 1, 1, 0, 1, 1, 0, 0], dtype=int64)

### Substituído os valores Vazios 

In [5]:
# Preenchendo os valores
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer = imputer.fit_transform(X[:, 1:8])

### Transformando os valores

In [6]:
# Lib
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
onehotencoder = make_column_transformer(
    (
        OneHotEncoder(categories='auto', sparse_output=False),
        [0]
    ), 
    remainder="passthrough"
)
X = onehotencoder.fit_transform(X)
X

array([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 337, 118, 4, 4.5,
        4.5, 9.65, 1],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 324, 107, 4, 4.0,
        4.5, 8.87, 1],
       [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 316, 104, 3, 3.0,
        3.5, 8.0, 1],
       [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 322, 110, 3, 3.5,
        2.5, 8.67, 1],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 314, 103, 2, 2.0,
        3.0, 8.21, 0],
       [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 330, 115, 5, 4.5,
        3.0, 9.34, 1],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 321, 109, 3, 3.0,
        4.0, 8.2, 1],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 308, 101, 2, 3.0,
        4.0, 7.9, 0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 302, 102, 1, 2.0,
        1.5, 8.0, 0]], dtype=object)

### Dividindo a base de Treino e Teste

In [7]:
# Treino e Teste
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2
)
X_train

array([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 314, 103, 2, 2.0,
        3.0, 8.21, 0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 316, 104, 3, 3.0,
        3.5, 8.0, 1],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 308, 101, 2, 3.0,
        4.0, 7.9, 0],
       [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 322, 110, 3, 3.5,
        2.5, 8.67, 1],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 302, 102, 1, 2.0,
        1.5, 8.0, 0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 324, 107, 4, 4.0,
        4.5, 8.87, 1],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 337, 118, 4, 4.5,
        4.5, 9.65, 1]], dtype=object)